name: Daily Job Scraper

on:
  schedule:
    - cron: '* * * * *'
    - cron: '0 9 * * 1-6'
    - cron: '0 13 * * 1-6'
    - cron: '0 17 * * 1-6'
  workflow_dispatch:

jobs:
  scrape-and-email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python scraper
        run: python scraper.py

      - name: Send email notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: '🚀 New Junior Developer Job Offers Digest'
          body: file://job_offers.html
          to: ${{ secrets.MAIL_TO }}
          from: GitHub Job Agent <${{ secrets.MAIL_USERNAME }}>
          content_type: text/html
